## From https://www.karelbemelmans.com/2016/10/deploying-a-hugo-website-to-amazon-s3-using-bitbucket-pipelines/
image: nixos/nix

pipelines:
  default:
    - step:
        script:
          - nix build .
          - nix shell nixpkgs#awscli
          - aws s3 sync --delete result/public s3://cacrawford.org
          ## Reset cloudfront cache. Not efficient, but works well since my site is small.
          - aws configure set preview.cloudfront true
          - aws cloudfront create-invalidation --distribution-id=E385LYO8Q21RUO --paths '/*' 
