## From https://www.karelbemelmans.com/2016/10/deploying-a-hugo-website-to-amazon-s3-using-bitbucket-pipelines/
image: atlassian/default-image:latest

pipelines:
  default:
    - step:
        script:
          - sh <(curl --insecure -L https://nixos.org/nix/install) --daemon
          - mkdir -p /etc/nix
          - echo "experimental-features = nix-command flakes" > /etc/nix/nix.conf
          - nix build .
          - nix shell nixpkgs#awscli
          - aws s3 sync --delete result/public s3://cacrawford.org
          ## Reset cloudfront cache. Not efficient, but works well since my site is small.
          - aws configure set preview.cloudfront true
          - aws cloudfront create-invalidation --distribution-id=E385LYO8Q21RUO --paths '/*' 
