## From https://www.karelbemelmans.com/2016/10/deploying-a-hugo-website-to-amazon-s3-using-bitbucket-pipelines/
image: karelbemelmans/pipelines-hugo

pipelines:
  default:
    - step:
        script:
          - hugo
          - aws s3 sync --delete public s3://cacrawford.org