baseURL = "http://cacrawford.org/"
languageCode = "en-us"
title = "Chad Crawford"
theme = "minimal"
# disqusShortname = "username" # delete this to disable disqus comments

[params]
    author = "Chad Crawford"
    description = "Personal blog, probably stuff about cats."
    githubUsername = "chadac"
    accent = "darkblue"
    showBorder = true
    backgroundColor = "#E9E9E9"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/publications/"
    name = "Publications"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4

[[menu.main]]
    url = "/cv/"
    name = "CV"
    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:chad@cacrawford.org"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/chadac/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://bitbucket.org/chadac/"
    name = "bitbucket"
    weight = 3

# [[menu.icon]]
#     url = "https://www.hackerrank.com/chadac"
#     name = "hacker"
#     weight = 4
