baseURL = "https://cacrawford.org/"
languageCode = "en-us"
title = "Chad Crawford"
theme = "hugo-theme-terminal"
paginate = 5

[params]
contentTypeName = "posts"
themeColor = "blue"
author = "Chad Crawford"
centerTheme = true
readingTime = true
authorDescription = "Software engineer, data engineer, data scientist. My blog talks about cool things I'd like to build."

[markup.goldmark.renderer]
unsafe = true

[[menu.main]]
url = "/"
name = "Home"
weight = 1

[[menu.main]]
url = "/posts/"
name = "Posts"
weight = 2

[[menu.main]]
url = "/about/"
name = "About"
weight = 3

[[menu.main]]
url = "/publications/"
name = "Publications"
weight = 4

[[menu.main]]
url = "/resume/"
name = "Résumé"
weight = 5

[[menu.icon]]
url = "mailto:chad@cacrawford.org"
name = "envelope-o"
weight = 1

[[menu.icon]]
url = "https://github.com/chadac/"
name = "github"
weight = 2

[[menu.icon]]
url = "https://bitbucket.org/chadac/"
name = "bitbucket"
weight = 3
